### ISSUE TITLE
Open a new viewer inside a viewer makes strange things

### ISSUE THREAD

**Issue by alixdamman** [liam2/larray#109]
and leads to a freeze.

**Comment by gdementen** [comment]
Unsure we can fix this (at least the session viewer with ipython/qtconsole part is problematic because of qtconsole which cannot "contain itself"). We should at least detect the case and either fail nicely or degrade to the simpler version instead (if possible).

**Comment by alixdamman** [comment]
Closed by PR #139

**Comment by gdementen** [comment]
mostly fixed in #139.
The only case which remains slightly problematic is view() (without argument) within view(), because the history of both consoles is somehow linked, and the synchronisation is not perfect.
