### ISSUE TITLE
Viewer - Some propositions for handling .h5 files

### ISSUE THREAD

**Issue by jehanneman** [liam2/larray#114]
It would be nice to be able to...

1. load another .h5 in addition to the one already loaded. For example we often load the population projection data next to the household data -> they're in 2 different .h5 files
2. prefix the names of the larray objects with the name of the .h5 file to make the distinction between objects coming from different .h5 files -> ex: **pop**.exi and **hh**.sing -> it would probably be interesting to make this optional because not necessary when only one .h5 object is opened
3. delete larray objects by selecting them in the left pane and deleting them with DEL button. This would be in addition to the already existing solution via a command line (which can be cumbersome if the list is long) 
4. same as 3. but for saving some larray's to another (new) .h5

**Comment by gdementen** [comment]
All individual points were split in separate issues, so closing this one.
