### ISSUE TITLE
implement arr2d @ arr1d

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#122]
currently the workaround is to:
```python
(arr2d @ arr1d.expand(Axis('bidulle', 1)))[x.bidulle[0]]
```

**Comment by bernhardmichel** [comment]
Another workaround:

(arr2d * arr1d).sum(x.axis1_arr2d)

**Comment by gdementen** [comment]
obviously, it would also be interesting to implement arr1d @ arr2d

**Comment by bernhardmichel** [comment]
Example:
# test arrays
arr2d = ndtest(((2, 3)))
arr1d = arr2d['a0'].copy()
# post-multiplication matricielle avec vecteur ne fonctionne pas
arr2d @ arr1d
# 2 workarounds
(arr2d * arr1d).sum(x.b)
(arr2d @ arr1d.expand(Axis('c', 1)))[0]
# pre-multiplication matricielle avec vecteur ne fonctionne pas
arr1d @ arr2d.transpose(x.b)
# 2 workarounds
(arr1d * arr2d).sum(x.b)
(arr1d.expand(Axis('c', 1)).transpose(x.c) @ arr2d.transpose(x.b))[0]
