### ISSUE TITLE
PR #124 broke a @ a.T

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#125]
Like I said in one of my reviews, __matmul__ must duplicate axes if the result ends up using twice the same Axis object. We should really add a test for this :)

**Comment by gdementen** [comment]
generally the unit tests for matmul are lacking some punch:
* no test for arr2d @ arr2d.T
* no test for arr4d(a,b,c,d) @ arr3d(e,d,f) -> arr5d(a,b,e,c,f)
* idem in reverse
* no test for arr4d(a,b,c,d) @ arr3d(b,d,f) -> arr4d(a,b,c,f)
* idem in reverse
* no test for arr4d(a,b,c,d) @ arr2d(d,f) -> arr5d(a,b,c,f)
* idem in reverse

**Comment by alixdamman** [comment]
When I started to generalize matmul for N dim, I thought the behavior of @ was the same as dot() function for N > 2. 
From Numpy doc ( https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.dot.html ), we read:

For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation). For N dimensions it is a sum product over the last axis of a and the second-to-last of b:

dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

This behavior of dot() simple. 

The behavior of @ is different and I wonder if we shouldn't restrict matmul to N <= 2? 
The original request was to use 1D and 2D arrays...

**Comment by gdementen** [comment]
In the long term, no we should not limit ourselves to N <= 2, but it's true N > 2 is clearly not a high priority for the moment, so we could simply raise NotImplementedError in that case, but since it might already work, it might be silly to do that instead of just adding tests to prove that it works :).

**Comment by alixdamman** [comment]
You make a point. 
Do I open an issue to implement a dot() function for LArray? It would be nice to have both since they are not really equivalent.

**Comment by gdementen** [comment]
Sure. Not high priority either but yes, something nice to have.
