### ISSUE TITLE
Add read_SDMX

### ISSUE THREAD

**Issue by alixdamman** [liam2/larray#146]
First with TSV files (with SDMX in the future)

**Comment by gdementen** [comment]
I wonder if this shouldn't be in another library on top of larray instead of in larray itself.

**Comment by alixdamman** [comment]
OK but load_sdmx should be implemented one day.

**Comment by gdementen** [comment]
move this issue to larray_eurostat?

**Comment by alixdamman** [comment]
As for TSV files, we could have a generic read_SDMX() in larray and a specific eurostat_SDMX_get() in larray_eurostat.

**Comment by gdementen** [comment]
oh, I thought SDMX was an eurostat specific format. Does Eurostat uses a specific dialect of SDMX?

**Comment by alixdamman** [comment]
No, SDMX is not specific to Eurostat. In eurostat_SDMX_get() we could as for eurostat_get() use a hard coded URL.

**Comment by gdementen** [comment]
make sense

**Comment by gdementen** [comment]
@gbryon has apparently implemented something like this using pandas_sdmx (both read and eurostat_sdmx_get), so we should check with him before (re)implementing this

**Comment by alixdamman** [comment]
Close this issue because it should be done in project https://github.com/alixdamman/larray_eurostat
