### ISSUE TITLE
Add title in all array creation functions. 

### ISSUE THREAD

**Issue by alixdamman** [liam2/larray#16]

**Comment by gdementen** [comment]
empty, ones, zeros, full, create_sequential, ndrange, ndtest, stack?, ... 

For example:
```python
ndrange('a=a0..a10', title='test array')
```

**Comment by gdementen** [comment]
Now that I think of it. The *_like functions should also have the argument to override the title, because it will usually be different from the source array. In fact, I am unsure it is a good idea to copy the title by default.

**Comment by gdementen** [comment]
(re-)closed by #27
