### ISSUE TITLE
document that read_eurostat/read_tsv/read_csv accept a file descriptor as input

### ISSUE THREAD

**Issue by alixdamman** [liam2/larray#162]

**Comment by gdementen** [comment]
In fact, it already accepts a file-like object, so we can use StringIO like in from_string if we want to pass it a string, or even use from_string(sep=..., headersep=...) directly.

**Comment by gdementen** [comment]
read_csv only fails with file-like objects for liam2 dialect, it would be nice to have an issue tracking this, but it is low priority to fix.
