### ISSUE TITLE
to_clipboard is broken

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#17]
The bug is in Pandas and/or in pyperclip (used by Pandas).
I suspect it is fixed in upstream pyperclip but not in the copy included in Pandas. So it might only needs a PR to pandas which simply updates pyperclip to the latest version.

**Comment by gdementen** [comment]
another option would be to bypass Pandas and use the code from pyqt. This however means you couldn't use the clipboard without qt installed. Does not seem too bad a restriction.

**Comment by alixdamman** [comment]
It works with version 0.19 of pandas.

**Comment by gdementen** [comment]
ok, nothing to do here then :)
