### ISSUE TITLE
make sure users can easily run tutorial code

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#170]
ie provide a way for users to easily get at the tutorial data (via a specific function?), like in stata et. al.

**Comment by alixdamman** [comment]
A specific function to generate the data or to download them?
Other question: 
Shouldn't we base our tutorial on some Eurostat data (or any public data)?

**Comment by gdementen** [comment]
Neither. Not generate because we want real data for the tutorial, not fake one. Not download it because we want users to be able to run the tutorial even without internet connection or if the URL breaks. What I meant was a function to load it from wherever the files live on their disk after having installed larray. For example, it might live in PYTHONDIR\Lib\site-packages\larray\tests\ and we do not want users to ever have to type that. Eurostat data is a good idea, but we need to have the license to distribute it however we want, which I don't know if it is the case.
