### ISSUE TITLE
update the release script

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#177]
It is becoming hard to remember to do everything when doing a release, so we should automate the process as much as possible. Here are a few steps:

- [x]  add new methods/functions in api.rst if not done yet (marked as done because I see no way to automate this)
- [x] update version (`meta.yaml`, `__init__.py` and `setup.py`)
- [x] update changelog date
- [x] git tag release
- [x] git push
- [x] build documentation (we can probably use hooks to get that done automatically)
- [x]  publish on pypi
- [x] update conda-forge feedstock to trigger new packages
- [x] update larrayenv
- [x] announce the release (once appveyor finally built the package for Windows :)) on larray-announce and possibly pyannounce or pydata or whatever.

**Comment by alixdamman** [comment]
Why did you add a bullet `build documentation (we can probably use hooks to get that done automatically)` ? The documentation is build automatically on readthedocs, no?

**Comment by gdementen** [comment]
Yes, but it was not at the time I created the issue!

**Comment by alixdamman** [comment]
assume #411 is done.

**Comment by alixdamman** [comment]
instead of rmtree, use `rd /s /q <directory>`.

**Comment by gdementen** [comment]
@alixdamman shouldn't this issue be closed?

**Comment by alixdamman** [comment]
Considering #411, we open a new issue or we edit this one?

**Comment by gdementen** [comment]
given #411 is closed, I guess we can close this issue, right?

**Comment by gdementen** [comment]
The release script needs to be updated to use the releaser lib. Do you prefer to keep this issue open for that or to close this issue and open a new one?

**Comment by alixdamman** [comment]
I opened a new issue : #537
