### ISSUE TITLE
implement .reindex_axis

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#18]
```python
>>> arr = ndtest((2, 3))
>>> arr.reindex_axis(x.a, ['a1', 'a0', 'a1', 'a3'])
a\\b |  b0 |  b1 |  b2
  a1 |   3 |   4 |   5
  a0 |   0 |   1 |   2
  a1 |   3 |   4 |   5
  a3 | nan | nan | nan
```
It might be easy to implement using something vaguely looking like:
```python
>>> new_axis = Axis(old_axis.name, new_labels)
>>> missing_value = missing[dtype]
>>> old_indices = old_axis.translate(new_labels, missing=-1)
>>> result = self.i[old_indices]
>>> # fix up those which were missing
>>> result[old_indices == -1] = missing_value
```

**Comment by alixdamman** [comment]
I do have the same problem as Pandas when working with integer arrays and trying to new labels : 
NaN are float.
http://pandas.pydata.org/pandas-docs/stable/gotchas.html#nan-integer-na-values-and-na-type-promotions

Do we chose to follow the same trade-off as Pandas, i.e. change dtype of the array from int to float ?

**Comment by gdementen** [comment]
I never liked that tradeoff, but we have no real choice in the short term here because using a flag value per type means we would need to override all aggregate and binary operations to explicitly check for that value and make it behave like nan do (propagate in binary ops). A large task in perspective. I wanted to go that route in LIAM2 (but never did so far because of the time it would take to implement).
