### ISSUE TITLE
rename create_sequential() to sequence()

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#212]
something like `create_seq()` or `sequence()` or even `seq()`

**Comment by gdementen** [comment]
@jehanneman suggests using sequential(), but he is not against sequence(). He mentions that zeros, ones etc also create an array and do not contain "create". 

My current favourite goes to sequence(). @alixdamman : what do you think?

**Comment by alixdamman** [comment]
Using an adjective as function name is weird for me. I would go for sequence() also.
