### ISSUE TITLE
better error message when trying to copy a sheet from one Excel instance to another using Workbook.__setitem__

### ISSUE THREAD

**Issue by alixdamman** [liam2/larray#231]

**Comment by gdementen** [comment]
I cannot reproduce this issue except when copying a sheet from another Excel instance, which is not supported by Excel. Was that what you tried? In that case, we could check if this is the case and produce a nicer exception.

**Comment by alixdamman** [comment]
Well, I messed up in my sandbox.py and unfortunately created 2 Excel workbooks. Then I tried to copy a sheet between the 2 workbooks leading to the expected crash.

**Comment by gdementen** [comment]
Here is a test case:
```python
>>> wb1 = open_excel()
>>> wb1['toto'] = 'hello'
>>> wb2 = open_excel()
>>> wb2['lulu'] = wb1['toto']
```
```python
com_error                                 Traceback (most recent call last)
...
com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', 'Copy method of Worksheet class failed', 'xlmain11.chm', 0, -2146827284), None)
```
