### ISSUE TITLE
consider changing string display of arrays

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#243]
ie, change the separator from " | " to "  " (two blanks) like Pandas.

```
a\b  b0  b1  b2
 a0   0   1   2
 a1   3   4   5
```
instead of:
```
a\b | b0 | b1 | b2
 a0 |  0 |  1 |  2
 a1 |  3 |  4 |  5
```
Pro: it makes for a slightly more compact representation, which can make a difference for wide arrays
Con: it makes it a tad less readable for narrow arrays (but that might be just because of what I am used to)

In either case, we need to decide whether we do it or not before implementing anything.

**Comment by alixdamman** [comment]
Other con: we will have to change a lot of doctests... 

But I do agree that the new representation will be more readable and less heavy. I would go for it (in release 0.23?)
