### ISSUE TITLE
labels are not checked during __setitem__

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#269]
```python
>>> arr = ndtest(3)
>>> arr
a | a0 | a1 | a2
  |  0 |  1 |  2
>>> arr2 = arr['a1:'].set_labels(x.a, 'b1,b2')
>>> arr2
a | b1 | b2
  |  1 |  2
# works when it should fail
>>> arr['a1':] = arr2
```
It was done on purpose to allow for:
```python
arr[['a0', 'a1']] = arr[['a1', 'a0']]
```
It would be a bit cumbersome to require a set_labels or drop_labels in this case, but it is probably worth it anyway because this is probably a rare operation and not checking can let errors pass silently which defeats the purpose of having labels in the first place.

```python
arr[['a0', 'a1']] = arr[['a1', 'a0']].drop_labels(x.a)
arr[['a0', 'a1']] = arr[['a1', 'a0']].set_labels(x.a, ['a0', 'a1'])
# assuming we have automatic align, we could express this with:
arr[:] = arr.set_labels(x.a, {'a0': 'a1', 'a1': 'a0'})
# or (if axis a contains more labels than just a0 and a1)
arr[['a0', 'a1']] = arr.set_labels(x.a, {'a0': 'a1', 'a1': 'a0'})
```
If one has only two values to swap, like above, one could write that as:
```python
a1 = arr['a1'].copy()
arr['a1'] = arr['a0']
arr['a0'] = a1
```

**Comment by alixdamman** [comment]
To solve this issue, my first thought is to use AxisCollection.check_compatible() in LArray.setitem 
but this may be a bad idea?

**Comment by gdementen** [comment]
It seems like a good idea. But it has been too long since I put my hands on that part of the code, so I cannot tell for sure. Try it and see how it goes.

**Comment by alixdamman** [comment]
Question:
The solution will break LArray.set() method (which basically call setitem) when passed value is a LArray with incompatible axis(es). 
Do we want the `set` method to behave like setitem (i.e. by checking axes compatibility)?

**Comment by gdementen** [comment]
That's fine for now I think (nobody use set anyway). In the future, we will align automatically, so that will be irrelevant.

**Comment by gdementen** [comment]
I would rather move this to 0.26 because of the potential code breakage

**Comment by gdementen** [comment]
Could you make a PR for this again?
