### ISSUE TITLE
change from_string sep default to ' '

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#271]
It would be very convenient to be able to use from_string directly on the output of an array (modulo \\ doubling)

Currently we need to specify sep manually:
```python
>>> from_string('''a\\b  b0  b1  b2
 a0   0   1   2
 a1   3   4   5''', sep=' ').info
2 x 3
 a [2]: 'a0' 'a1'
 b [3]: 'b0' 'b1' 'b2'
```

**Comment by alixdamman** [comment]
I agree.
