### ISSUE TITLE
provide a way to run the viewer standalone easily

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#281]
One way to do it would be to use menuinst in the conda package.
https://conda.io/docs/building/recipe.html#adding-windows-start-menu-items
https://github.com/ContinuumIO/menuinst/wiki

Another, more involved way would be to create an installer for the whole thing (e.g. using NSIS or Innosetup). In the long run I think we will be better off with this option, but this is a lot more upfront work.

**Comment by alixdamman** [comment]
I am making progress although the wiki of menuinst is written as "trek je plan". 
Do we have a logo (icon) for LArray?

**Comment by gdementen** [comment]
We do not have a logo/icon so far.

**Comment by alixdamman** [comment]
Put that here as a reminder:
1) menuinst is a dependency of conda, no need to install it.
2) menuinst.install(..., remove=False/True) is automatically called with '> conda install/remove some_package'.

**Comment by alixdamman** [comment]
Transferred to https://github.com/larray-project/larray-editor
