### ISSUE TITLE
.axes not in documentation

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#301]

**Comment by gdementen** [comment]
In fact it is, but only in `LArray.__init__` while users understandably looked for it in the "inspecting" section. Unsure whether fixing #302 would change anything in this regard.

**Comment by alixdamman** [comment]
documenting class instance attribute is not implemented in current Sphinx (1.5.1).

https://github.com/sphinx-doc/sphinx/issues/3257

**Comment by alixdamman** [comment]
One way would be to implement a property axes

**Comment by gdementen** [comment]
I do not like changing the code/functionality just for the documentation, so I would do this as a last resort (we would need a property for .data too) and either change the code to use ._data and ._axes (the real fields behind the property) everywhere (ugly and not fun to change) or incur a performance penalty. 
From the linked issue I get we cannot have this automatically (using autosummary), but can't we do this manually (ie add the documentation directly in api.rst)?

**Comment by alixdamman** [comment]
Well, I had the same thought about creating a property. I wanted to include the entries for `axes` and `data` in the table generated by the command autosummary. I'll explore what would be the best solution.
