### ISSUE TITLE
replace DeprecationWarning (et al?) by FutureWarning so that users see them

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#310]
... but we want our users to see them.

There are several options to see them, none of which seems very appealing.

* advise our users to systematically add this to all their modules:
```python
import warnings
warnings.filterwarnings("default", category=DeprecationWarning, module="__main__")
```
... but this is tedious and they will not do it.
* advise our users to run their interpreter with -W
a bit hard to explain how to do that but less tedious. The problem is that they get lots of deprecation warnings from internal code (eg. ipython using deprecated zmq api), which makes it almost useless.
* use FutureWarning instead of DeprecationWarning everywhere.
in that case, we have what we want when users run their models but loose a nifty PyCharm feature which strikes through all functions which "raise" a DeprecationWarning.
* try to come up with some insane code which does something like the first point automatically by inspecting the frame to see who imported larray.

PS: This is the case since 2.7 and the reasoning was that end-users (those using programs written in Python) should not see those kinds of warnings and that developers should run with -W anyway.

**Comment by alixdamman** [comment]
I already used FuturWarning for ipfp. Replacing DeprecationWarning by FuturWarning is my favorite option.

**Comment by gdementen** [comment]
Yes, but in that case, you did not loose PyCharm's feature anyway.

**Comment by alixdamman** [comment]
which feature?

**Comment by gdementen** [comment]
In user code, it strikes through functions which are deprecated

**Comment by gdementen** [comment]
a few more options, for completeness:
* emit both
* detect if DeprecationWarnings are ignored, if so emit a FutureWarning (or both), otherwise emit only a FutureWarning
* add `warnings.simplefilter('default', DeprecationWarning)` somewhere in larray code, but explicitly ignore all warnings we are aware of by wrapping them in:
```python
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
```
But I think simply using a FutureWarning is our best option anyway.
