### ISSUE TITLE
make edit(REOPEN_LAST_FILE) reload the last opened file

### ISSUE THREAD

**Issue by alixdamman** [liam2/larray#315]
As for open_excel. 

This is a nice to have after PR #299 (standalone editor).

**Comment by gdementen** [comment]
That would be nicely consistent with open_excel, but I do not see an actual use case for it. Do you have one in mind/stumbled upon a situation where this would have been useful?

**Comment by alixdamman** [comment]
Situation? The standalone version of the editor.

**Comment by gdementen** [comment]
Oh, you meant the last open file (from recent files). Now I get it. Well using -1 for this might be confusing because it is similar but slightly different from open_excel(-1)
