### ISSUE TITLE
try to have conf.py version automatically update

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#318]
Originally at: https://github.com/liam2/larray/pull/317#issuecomment-308383904

    Question : In xarray (but also Pandas if I remember well), the conf.py ( https://github.com/pydata/xarray/blob/master/doc/conf.py ) contains the following lines:

    import xarray
    release = xarray.version

    Can't we do the same?

**Comment by alixdamman** [comment]
Yes, it's working : http://larray-test.readthedocs.io/en/documentation/
