### ISSUE TITLE
deprecate names argument of Session.save and to_*

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#321]
Assuming a session s:
```python
>>> s = Session(a=ndtest(2), b=ndtest(3), c=ndtest(4))
```
Instead of:

```python
>>> s.save('test.h5', ['a', 'b'])
```
Users should use this instead:
```python
>>> s['a', 'b'].save('test.h5')
```

**Comment by gdementen** [comment]
In fact, I am unsure about this because on one hand, those are two ways to do exactly the same thing and the (would be) deprecated way is a tiny bit longer, but on the other hand, the deprecated way is symmetric with .load(names=) so might be more obvious for users?

**Comment by alixdamman** [comment]
I would keep names arg. and avoid to have 2 different syntax for load and save.

**Comment by gdementen** [comment]
Ok, closing.
