### ISSUE TITLE
viewer functions documentation does not appear in the rendered documentation

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#322]
I guess this is because the doc is picked up from the "dummy" versions which are used when Qt is not available (because pyqt it is not installed on the readthedocs server?).

One way to fix this would be to copy the docstring to those functions (and change their signature) from the "real" functions.

**Comment by gdementen** [comment]
This is again the case in 0.25

**Comment by alixdamman** [comment]
I think the true solution is larray-editor having its own documentation and to use intersphinx.
