### ISSUE TITLE
implement LArray.__contains__

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#343]
Currently `__contains__` checks on values, and not on axes labels. I wonder if the later would not be more logical, as LArrays are more dict-like than list-like.

```python
>>> a = ndtest(4)
>>> a
a  a0  a1  a2  a3
    0   1   2   3
>>> 2 in a
True
>>> 'a2' in a
False
```
the idiom:

```python
if key in array:
    value = array[key]
    # do something
```
can be useful.

However, the current behaviour can also be useful, especially for 1D arrays, so providing another way to do it is required.

**Comment by alixdamman** [comment]
I think `__contains__` should check on axes labels. This makes more sens to me. 
To iterate on values, we could add a `values` method and do:
```python
if value in array.values():
    #do something    
```

**Comment by gdementen** [comment]
I would rather have users simply use:
```python
if value in array.data:
    # do something
```
which already works.
