### ISSUE TITLE
make combine_axes and boolean selection use same sep

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#376]
combine_axes defaults to `_` and boolean selection defaults to `,` and this makes them incompatible by default. Unsure which we should choose (probably `_` to not piss off Bernard ;-)). Unsure if issuing a warning first (for a few release) will be possible/practical.

This is required for #369.

**Comment by alixdamman** [comment]
I would go for `_` (I think `_` has no particular meaning in the case of the "string" syntax of LArray). 
I guess boolean filtering will return a "MultiIndex" version of an LArray in the future.

**Comment by gdementen** [comment]
For axes names `_` is mostly equivalent to `,` (at least at this point -- until we implement #358). But for actual labels, I think `,` was superior since it had the nice property that you could (\*) use a label of the combined axis as a key in the split array and it worked. 

(\*) actually, it did not work but it could be made to work, so that does not change my point. Depending on how fast we implement #28, spending much time on this might not be worth it.
