### ISSUE TITLE
combine several axes lists at once in combine_axes 

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#382]
See also #366 

Possible syntaxes:
```python
>>> arr.combine_axes({('a', 'b'): 'ab', 'c,d': 'cd'})

>>> # or the opposite
>>> arr.combine_axes({'ab': ('a', 'b'), 'cd': 'c,d'})
>>> # which would allow the nicer syntax:
>>> arr.combine_axes(ab=('a', 'b'), cd='c,d')
```
The problem with this "opposite" syntax is that it is not consistent with (it is the inverse of) how arr.rename, arr.set_axes and arr.set_labels work, which use from, to instead of to, from:

```python
>>> arr = ndtest((2, 3))
>>> arr
a\b  b0  b1  b2
 a0   0   1   2
 a1   3   4   5
>>> arr.rename('a', 'c')
>>> arr.rename({'a': 'c'})

>>> arr.set_axes(a='c=0..6')
>>> arr.set_axes({'a': 'c=0..6'})

>>> arr.set_labels({'a': '0,1'})
```

**Comment by alixdamman** [comment]
The syntax
```python 
>>> arr.combine_axes(ab=('a', 'b'), cd='c,d')
```
do not allow to use special characters in axis names. 

To be consistent with `rename`, `set_axes`, ... I would choose the first syntax (from, to).

**Comment by gdementen** [comment]
Indeed, but
```python
>>> arr.combine_axes({'ab': ('a', 'b'), 'cd': 'c,d'})
```
would allow special characters, and in rename and set_axes we support both a dict and **kwargs too (for that reason).

The question was in fact whether or not to change the syntax for rename, set_axes and set_labels because with the keyword syntax, the "inverted" syntax reads better/is a lot more logical than the current syntax: you **assign** something to the new name, in the same way you assign a variable.

```python
>>> arr.rename(c='a')
```
but I just realized this only works for rename and not for set_axes and set_labels, so the question is closed.

**Conclusion**: let us just implement the first syntax:

```python
>>> arr.combine_axes({('a', 'b'): 'ab'}
```

**Comment by alixdamman** [comment]
to simplify the implement of this, can I add a `name` argument in `AxisCollection.combine_axes` (assuming we use a dict in `LArray.combine_axes`)?

**Comment by alixdamman** [comment]
You want both `LArray.combine_axes` and `AxisCollection.combine_axes` to combine several axes lists at once or just `LArray.combine_axes`?

**Comment by gdementen** [comment]
For consistency's sake, I would rather go for both, if that is not too hard to implement.

**Comment by alixdamman** [comment]
I need to summarize before to go further:
* `axes` argument of  both `LArray.combine_axes` and `AxisCollection.combine_axes` accept tuple, list, AxisCollection AND **dict with entries {axes_to_combine: new_axis_name}**
* `axes` argument of  both `LArray.split_axes` and `AxisCollection.split_axes` accept tuple, list, AxisCollection AND **dict with entries {axis_to_split: new_axes_names}**
* to be consistent with `split_axis`, we add an argument `name` used only if `axes` is not a dict
Is that correct?

**Comment by alixdamman** [comment]
I am starting to wonder if some creative users will ask for different delimiters ('_' for the first group of axes to combine, '/' for the second group, ...)

**Comment by gdementen** [comment]
That seems weird/rare enough that I have no trouble to tell them to call the method several times, as currently.
