### ISSUE TITLE
na, sort_columns, sort_rows silently ignored in read_excel

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#393]
When using xlwings backend, which is the default

**Comment by gdementen** [comment]
Ideally we should implement them (by passing the arguments down all the way to df_aslarray), but raising an explicit error would already be better than the current situation.

**Comment by gdementen** [comment]
Here is a test case whenever we want to implement the na argument for xlwings:

```python
>>> arr = ndtest((2, 2, 2), dtype=float)
>>> arr['a1', 'b0'] = np.nan
>>> arr
a	b\c	c0	c1
a0	b0	0.0	1.0
a0	b1	2.0	3.0
a1	b0	nan	nan
a1	b1	6.0	7.0
>>> arr.to_frame(dropna='any', fold_last_axis_name=True).to_excel('test.xlsx', merge_cells=False)
>>> read_excel('test.xlsx', na=42)
a	b\c	c0	c1
a0	b0	0.0	1.0
a0	b1	2.0	3.0
a1	b0	nan	nan
a1	b1	6.0	7.0
>>> read_excel('test.xlsx', na=42, engine='xlrd')
a	b\c	c0	c1
a0	b0	0	1
a0	b1	2	3
a1	b0	42	42
a1	b1	6	7
```

**Comment by alixdamman** [comment]
xlwings includes a Pandas Converter and allows to define UDF (user defined function). Shouldn't we use them?
