### ISSUE TITLE
rename na argument in read_* to fill_value (and improve its description) 

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#394]
The problem is that its meaning is ambiguous: one could think it replaces nan/empty/invalid cells in the file with the passed value, while it is only used as a fill value when "densifying" sparse data .

**Comment by alixdamman** [comment]
For the description, what about:
```python
    fill_value : scalar, optional
        Value used to fill data of extracted LArray with no corresponding value in CSV/Excel/HDF/SAS file. 
        Defaults to NumPy NaN.
```
?

**Comment by gdementen** [comment]
FWIW, in reindex (which is basically the same thing), we use:

    fill_value : scalar or LArray, optional
        Value set to data corresponding to added labels. Defaults to NaN.

I don't know which is better, but I guess we should be consistent.

Maybe changing them all (reindex included) to something like:

    fill_value : scalar or LArray, optional
        Value used to fill cells corresponding to label combinations which are not present in the input. Defaults to NaN.

It might be worth it to search the code for other methods having a fill_value argument and make them all consistent.
