### ISSUE TITLE
provide larrayenv package

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#40]
which depends on larray and all optional larray dependencies so that our users only need to do:
```
conda update larrayenv
```
and be sure to have all the functionalities installed.

**Comment by alixdamman** [comment]
In which channel?

**Comment by gdementen** [comment]
For 0.19.1, I will do it using the current "gdementen" channel. For 0.20, we will use conda-forge.

**Comment by gdementen** [comment]
conda metapackage larrayenv 0.19 --dependencies 'larray ==0.19' qtconsole matplotlib pyqt qtpy pytables xlsxwriter xlrd openpyxl xlwings

**Comment by gdementen** [comment]
I added a make_meta_package.bat batch file a while ago which should help us do this. Now we only need to remember updating it when we add/remove dependencies and to call it for each release.
