### ISSUE TITLE
implement Axis.contains (or Axis.containing?)

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#402]
```python
>>> a = Axis("a=ac0,bc1,ad2,bd3")
>>> a.contains('a')
a['ac0', 'ad2']
>>> a.contains('c')
a['ac0', 'bc1']
>>> a.contains('b')
a['bc1', 'bd3']
>>> a.contains('d')
a['ad2', 'bd3']
```
To be honest, I think we should name it "containing" instead of "contains" because contains should return a boolean, but in that case we should also rename `startswith` to `startingwith`, `endswith` to `endingwith` and `matches` to `matching`. I think we should do that. If you agree, I will open a new issue for that.

**Comment by gdementen** [comment]
@alixdamman your thoughts?

**Comment by alixdamman** [comment]
Or use `labelswith` instead of `containing`?

**Comment by alixdamman** [comment]
In any case, I don't think it's necessary to rename starts/endswith and matches.

**Comment by gdementen** [comment]
IMO `arr[code.containing('ABC')]` reads better/is more intuitive than `arr[code.labelswith('ABC')]`

**Comment by alixdamman** [comment]
Well, OK. But I'm still not sure about renaming other methods.
