### ISSUE TITLE
Add Workbook methods in documentation

### ISSUE THREAD

**Issue by alixdamman** [liam2/larray#409]
open_excel returns a Workbook but Pycharm does not know that and does not provide completion.

**Comment by gdementen** [comment]
Yes, those should somehow appear in the API doc. Unsure what is the best way to achieve that though.

**Comment by alixdamman** [comment]
My idea is to add more examples in docstring of open_excel and to update the section "more Excel IO" in the tutorial. Doing it in the API is a bad idea since Readthedocs will skeep all docstrings of Workbook methods.

**Comment by gdementen** [comment]
I think the correct way to do this would be to add the Workbook class to the API and possibly deprecate open_excel (in favor of using Workbook directly).

**Comment by alixdamman** [comment]
The Workbook class is not parsed by Readthedocs (because of the `if xw is not None`). Sorry but I don't see your point?

**Comment by alixdamman** [comment]
One way to add documentation of Workbook would be to add this class with empty methods after the `else:` and then use `.__doc__` to define the documentation. 
Exactly as we do for `open_excel`. 

If we create an "empty" Workbook, deprecate `open_excel` would be nice (but maybe too soon for our current users).
