### ISSUE TITLE
remerge larray-editor project?

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#411]
Conda actually supports creating several packages from a single repository. We could **probably** create the larray, larray-editor and larrayenv packages using a single recipe. We need to investigate whether that is actually possible but it would streamline our workflow quite a bit if it is.

https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#implicit-metapackages

**Comment by alixdamman** [comment]
In that case, we will still have only one setup.py or one per sub-package?

**Comment by alixdamman** [comment]
abandoned

**Comment by gdementen** [comment]
For future reference, it was abandoned because we hope to make larray-editor not dependent of larray in the future. For that to be useful, we will need to make it able to view/edit other array structures directly (eg. np.ndarray, pd.DataFrame, xarray, ...)
