### ISSUE TITLE
dist packages are missing larray/tests .csv files

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#419]
* all tests files in larray/tests are missing, so one cannot run all larray tests when downloading the package from pypi or conda.
* larray/tests/data contains the generated data.h5 and data.xlsx

This makes packages on pypi and conda more than 3 times as big as they should be.

**Comment by alixdamman** [comment]
the file data.h5 is required to call function load_example_data() (see example.py)

**Comment by gdementen** [comment]
hmmm and data.xlsx is used in the tutorial... Unsure why pycharm showed those as not being tracked by git?! So I thought those were generated files from my local copy.

**Comment by gdementen** [comment]
Sorry for the noise then.

**Comment by gdementen** [comment]
see #421 for the followup.
