### ISSUE TITLE
add docstrings (& examples) for aggregate methods

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#43]
We might want to use a template for part of it.

**Comment by alixdamman** [comment]
Since aggregate functions are also defined outside LArray class, can I do something like https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.sum.html#numpy.ndarray.sum ?

**Comment by gdementen** [comment]
Sure, but I wonder if doing the opposite (have the full doc in the method and link to it in the function) wouldn't be better in this case. The reason is that I prefer when people use the methods over the functions. The functions are only there so that they can be used in with_total.
