### ISSUE TITLE
when saving a file under an existing name fails, the file is deleted anyway

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#441]
This is extremely annoying. I had a large (valid) file, I introduced a few bad values in it, tried to save it. It failed (without error, see larray-project/larray-editor#75) and I then closed the editor to realize my file had disappeared, hence loosing my work!

This happens at least for saving to Excel, but might happen for other backends too.

This is going to be a tad annoying to fix:

```
if destpath exists:
    if overwrite:
        save file as temppath
        delete destpath
        rename temppath to destpath
    else:
       raise "{despath} already exists"
else:
    save file as destpath

```
Or, a tad simpler (but at tad less efficient):    

```
save file as temppath
if destpath exists:
    if overwrite:
        delete destpath
    else:
        raise "{despath} already exists"
rename temppath to destpath
```

**Comment by alixdamman** [comment]
I think that the problem comes from `Workbook.__init__` in which we find the 4 following lines:
```python
    if os.path.isfile(filepath) and overwrite_file:
        os.remove(filepath)
    if not os.path.isfile(filepath):
        self.new_workbook = True
```
So, I guess only Workbook must be changed.

**Comment by gdementen** [comment]
The problem is also present in Session.save():

```python
        if overwrite and engine != ext_default_engine['csv'] and os.path.isfile(fname):
            os.remove(fname)
```
