### ISSUE TITLE
reading an Excel sheet with invisible/blank cells should strip them by default

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#443]
see attached file
[bad.xlsx](https://github.com/liam2/larray/files/1320676/bad.xlsx)

```python
>>> read_excel('bad.xlsx', 'bad')
 a\b  2003  2004  None  None  None
  a0   0.0   1.0  None  None  None
  a1   2.0   3.0  None  None  None
None   nan   nan  None  None  None
```
* It should only strip bottom-right blanks
* Unsure the nans should be stripped. We need to investigate why those cells are different from the None cells.
* Unsure having the option to avoid stripping is worth it (let's say no until somebody requests this).

**Comment by alixdamman** [comment]
for some reasons, `read_excel(fpath, 'bad', engine='xlrd')` seems to work perfectly.

**Comment by gdementen** [comment]
I guess either pandas or xlrd does the stripping. 
This is most likely because of this line: https://github.com/liam2/larray/blob/master/larray/io/excel.py#L325
Unsure how to work around this.

**Comment by gdementen** [comment]
Here is another case I would like to support:
[bad.xlsx](https://github.com/liam2/larray/files/1343427/bad.xlsx)

**Comment by alixdamman** [comment]
See # see https://www.excelcampus.com/vba/find-last-row-column-cell/#endcode for some ideas

**Comment by alixdamman** [comment]
```python
        @property
        def shape(self):
            # XXX: requires xlwings 0.9+
            used = Range(self, 'A1').xw_range.current_region
            return used.shape
```
is working as long as there is no internal blank row/column
