### ISSUE TITLE
Display dtype when printing an array (+ .info)

### ISSUE THREAD

**Issue by alixdamman** [liam2/larray#454]

**Comment by alixdamman** [comment]
Question: Do we display `dtype` only when calling `info` or also each time we display an array?

**Comment by gdementen** [comment]
Unsure about when printing the array but we need it in .info for sure.

**Comment by gdementen** [comment]
maybe we could do .info now, see how it goes and add it in __repr__ later if needed (and it does not look too ugly, which I am afraid it will).
