### ISSUE TITLE
#381 followup: formalizing our unstructured format and conversion from dataframe

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#460]
* df_as_larray should have a flag (False by default and True when calling it from readcsv).
  if False, df_as_larray should **always** return at least a 2D LArray (more than 2D when there are MultiIndex involved).

* when called from read_csv, I think we should make the difference between 1D and 2D by using whether or not the dataframe has length 1 and the first cell on the second line is blank:
if len(df) == 1 and np.isnan(df.iloc[0, 0])

```
sex, 2015, 2016
  F,    0,    1
  M,    2,    3
```
```
sex\{1}  2015  2016
      F     0     1
      M     2     3
```
===
```
time, 2015, 2016
    ,    0,    1
```
```
time  2015  2016
         0     1
```
===
```
time, 2015
    ,    0
```
```
time  2015
         0
```
===
```
, 2015
,    0
```
```
{0}  2015
        0
```
===
```
sex, 2015
  F,    0
```
```
sex\{1}  2015
      F     0
```
===
```
sex, 2015
  F,    0
  M,    1
```
```
sex\{1}  2015
      F     0
      M     1
```
===
```
 , 2015
F,    0
M,    1
```
```
{0}\{1}  2015
      F     0
      M     1
```
and I think it would be consistent if we supported to also define 1D arrays this way:
```
sex,
  F, 0
  M, 1
```
```
sex  F  M
     0  1
```
```
 ,
F, 0
M, 1
```
```
{0}  F  M
     0  1
```

I let you translate what each of those .csv files would mean in terms of dataframes...

**Comment by alixdamman** [comment]
It concerns also Excel files no?

**Comment by gdementen** [comment]
Yes, of course. I should have said from "unstructured" file formats :)

**Comment by alixdamman** [comment]
Waiting for PR #381 before to start.

**Comment by alixdamman** [comment]
If we go trough the idea of having `io_df_aslarray` and `from_frame`, I still don't know what to do with 1xN DataFrame inside `from_frame` --> returns an LArray of shape (1, N) or (N,) ?

I suggest to have both `from_frame` and `from_series`.

**Comment by gdementen** [comment]
There is still one thing bothering me. Files without any index column/unique identifier will not load correctly. And with the introduction of LFrame in a few releases, this will be a problem if we want to use the same function to load frames and arrays.

```
sex, age, education
  F,  45,  tertiary
  F,  15, secondary
  M,  35,  tertiary
```

At a minimum, we need to be able to:
* convert the dataframe created by reading that dataframe with pd.read_csv
* read it using la.read_csv(nb_index=0)

but I **wonder** if we might not want to leave intact that "rangeindex" that pd.read_csv produces by default when we do not find a `\` in the axe names, nor the empty/nan cell marker for 1D arrays. 


FWIW, the classical DB format like the following, which I think works with your current changes, would not work anymore but would require nb_index=1 to achieve what we want.
```
id, sex, age
 0,   F,  23
 1,   M,  21
```
by default:
```
{0}\{1}  id  sex  age
      0   0    F   23
      1   1    M   21
```
with nb_index=1
```
id\{1}  sex  age
     0    F   23
     1    M   21
```

Other casualties of this change would be this:
```
sex, 2015, 2016
  F,    0,    1
  M,    2,    3
```
which would produces by default:
```
{0}\{1}  sex  2015  2016
      0    F     0     1
      1    M     2     3
```
nb_index=1
```
sex\{1}  2015  2016
      F     0     1
      M     2     3
```

**Comment by gdementen** [comment]
> If we go trough the idea of having io_df_aslarray and from_frame functions, I still don't know what to do with 1xN DataFrame inside from_frame --> returns an LArray of shape (1, N) or (N,) ?

I think (1, N) would be saner. A bit less practical for 90% of (1, N) cases, but simpler/more predictible (which is arguably more important than being practical). DF -> LArray => always 2D.

> I suggest to have both from_frame and from_series.

Yes. Sure. That can come later though. Might want to create an issue for this.

**Comment by alixdamman** [comment]
If DF -> LArray with dim >= 2 and if `io_df_aslarray` calls `from_frame` (as suggested), it means that it becomes impossible to read 1D array from CSV or Excel or HDF files.

**Comment by gdementen** [comment]
This is solvable. Either
* io_df_aslarray and from_frame must both call another private method.
or
* io_df must modify the larray it receives from from_frame.

There are probably other options. The first goal/the most important part is
to make them do "the right thing". Then we can see how to avoid duplicating
too much code between them (which was the idea behind io_df calling
from_frame). But the second part should not hinder the first.

**Comment by alixdamman** [comment]
IMO, io_df should call either `from_series` or `from_frame`.

**Comment by alixdamman** [comment]
implementing `from_series` is not that hard and I think this is the right moment to do it.

**Comment by gdementen** [comment]
Yes, if that works, that would probably be cleaner than what I suggested.
But we need to agree on the desired result of both functions before how to
implement them.

**Comment by alixdamman** [comment]
As I see them, `from_series` should returns a 1D LArray and `from_frame` an >= 2D LArray.

**Comment by gdementen** [comment]
no, from_series an at least 1D LArray. Series can have a multi-index.
BTW: from_frame should handle a dataframe with a multi-index in columns, which I do not think it handles currently. That could come later but in that case the limitation should be clearly documented.
