### ISSUE TITLE
fix readthedocs PDF

### ISSUE THREAD

**Issue by alixdamman** [liam2/larray#461]
HTML build seems to crash since commit b38a04b677e233e3e60ddfdd110594b76da9a58b (implemented nan_equal ) with message `Illegal instruction`.

PDF build crashes since commit 944d8f422d44c76221d227e14f4325d0bd3e4140 (fix #450 : implemented deprecated decorator).

**Comment by alixdamman** [comment]
The message `error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory` is present since a long time ago. It is not the source of the crash.

**Comment by gdementen** [comment]
one of those errors might be related to the fact that AxisCollection.split_axis is missing

**Comment by gdementen** [comment]
Since sphinx's  autodoc executes module-level code, I guess this is the problematic line (for some reason):

```python
obj_isnan = np.vectorize(lambda x: x != x, otypes=[bool])
```

**Comment by alixdamman** [comment]
It seems that the problem with the HTLM has been solved. 
However, the problem with the generation of the PDF remains.

**Comment by gdementen** [comment]
Did readthedocs change something or did you find what was causing the
problem on our side?

**Comment by alixdamman** [comment]
It's not me. Something changed in readthedocs.
