### ISSUE TITLE
position or index

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#50]
We should pick one of the two terms and stick with it. Currently we use both (.i and .ipoints but PGroup and posarg*). We should either have:
.p[], .ppoints[], PGroup and posarg*
or
.i[], .ipoints[], IGroup and iarg* (or indarg*)

**Comment by alixdamman** [comment]
I would go for index. For me, position is more link to a "geographical" position or position in space.

**Comment by gdementen** [comment]
I like personally this but I would have asked a few users what they think before implementing this, because I wonder if positions is not more telling to a random user than indices??

**Comment by gdementen** [comment]
see #197
