### ISSUE TITLE
Where should report issue... report issues?

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#519]
It reports issues on liam2/larray but we might want to report them on larray-editor instead?

Or ideally, let the user choose (but then we need to explain what to report where).

**Comment by alixdamman** [comment]
Considering #411, should be done in liam2/larray.

**Comment by gdementen** [comment]
given we closed #411, the question still stands :)

**Comment by alixdamman** [comment]
I know and this issue should moved to larray-editor right?
My answer is that we should let user choose.

**Comment by gdementen** [comment]
> this issue should moved to larray-editor right?

Indeed, sorry, I just used the "report issue..." link to get here :)
