### ISSUE TITLE
rename 'nb_index' arg of read_XXX as 'nb_axes'

### ISSUE THREAD

**Issue by alixdamman** [liam2/larray#548]
@gdementen I understand why using 'nb_index' in the context of Pandas but since the function `read_csv` of larray returns an LArray object, I'm not sure I want to keep `nb_index`. What do you think?

**Comment by gdementen** [comment]
Yes, it makes a lot of sense to change that. The backward compatibility decorator will need to be updated to take a function which translates the old value argument to the new one because in this case nb_axes = nb_index + 1
