### ISSUE TITLE
implement ability to change the default name of last column in to_csv/excel when wide=False

### ISSUE THREAD

**Issue by alixdamman** [liam2/larray#549]
@gdementen 

The flag `transpose` in `to_csv` is nice but creates an extra axis with a default name (an integer). 
Btw, users may want to change that meaningless default name.
So when you try to read the CSV file after, you get an LArray object with shape like 
'axis1 (10) x axis2 (16) x axis3 (8) x default (1)' and then you need to reshape the array to get rid of this last axis.  

Do you think it worth to do something about it?

**Comment by gdementen** [comment]
+1 for an ability to change that name (and have some something more sensible as default, like "value")
+1 for being able to read that back nicely, though I don't know how to improve on the current situation. Please provide mockup syntaxes and (tiny) output examples.
Btw: In this situation, I have so far told our users to use ['label_of_default_axis'] to get rid of it. It is simpler than reshape.

**Comment by alixdamman** [comment]
@gdementen rename argument `transpose` as `vertical` or `data_to_column`?

**Comment by gdementen** [comment]
I have never heard it called "vertical". 
* [Wikipedia](https://en.wikipedia.org/wiki/Wide_and_narrow_data) speaks about wide and narrow (sometimes un-stacked and stacked, or wide and tall) 
* [Pandas](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.melt.html) uses wide and long

From a quick google search, the most common of the terms above seems to be "wide". So use wide=True instead?

**Comment by alixdamman** [comment]
OK for wide. We need to add some explanation/examples in the tutorial ;)
