### ISSUE TITLE
rename to_excel sheet_name to sheet

### ISSUE THREAD

**Issue by gdementen** [liam2/larray#580]
since sheet_name can also be a sheet index, sheet seems more appropriate than sheet_name.

**Comment by Avasse** [comment]
Hi, i'd be glad to work on this issue, is anybody working on it ?

**Comment by alixdamman** [comment]
@gdementen any objections?

**Comment by Avasse** [comment]
I already read the "How to contribute" http://larray.readthedocs.io/en/stable/contribute.html#sending-your-changes" 

And did some changes to fit that issue. (See : https://github.com/liam2/larray/pull/583) As it is my first PR, telle me if i did anything wrong please. Thanks you !

**Comment by gdementen** [comment]
@alixdamman no, but that assumes you agree with the change...

**Comment by alixdamman** [comment]
@gdementen @Avasse I agree with the change.

**Comment by gdementen** [comment]
closed by de449aa
