### ISSUE TITLE
Add Menu File with Open, Save, Save As and Exit 

### ISSUE THREAD

**Issue by alixdamman** [liam2/larray#88]

**Comment by gdementen** [comment]
we need to be able to load a second .h5 along side the current session (see #114).

**Comment by alixdamman** [comment]
Question: Why MappingEditor and ArrayEditor are QDialog and not QMainWindow?
Because of Spyder? 

I'm asking because it would be much more easier and suitable to use a QMainWindow instead of QDialog to add a menu bar.
